# Generated by Django 3.2.25 on 2024-06-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0002_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
