# Generated by Django 3.2.25 on 2024-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0003_rename_appointments_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_name',
            new_name='firstname_patient_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='passport_umber',
            new_name='passport_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='Medicalhistory',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='conditions',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fee',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnant',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referredBy',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='remarks',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondname_patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='specialization',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
