# Generated by Django 3.2.25 on 2024-06-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0005_auto_20240630_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Phone_number',
            new_name='second_phone_number',
        ),
    ]
