# Generated by Django 3.2.25 on 2024-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0006_rename_phone_number_patient_second_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
