# Generated by Django 3.2.25 on 2024-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0009_auto_20240630_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pateint_id',
            new_name='patient_id',
        ),
    ]
