# Generated by Django 3.2.25 on 2024-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0011_auto_20240630_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Doctor'), ('S', 'Staff')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventappointment',
            name='treatment',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
