# Generated by Django 3.2.25 on 2024-07-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0012_auto_20240630_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventappointment',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
