# Generated by Django 3.2.25 on 2024-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0013_eventappointment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
