# Generated by Django 3.2.25 on 2024-07-06 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0018_alter_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=13, null=True)),
                ('time', models.CharField(choices=[('AM', 'AM'), ('NOON', 'NOON'), ('PM', 'PM')], max_length=10)),
                ('Medicine_choice', models.CharField(choices=[('B', 'Before Meal'), ('A', 'After Meal')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='q1bapp.patient')),
            ],
        ),
    ]
