# Generated by Django 3.2.25 on 2024-07-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0019_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine_choice',
            new_name='medicine_choice',
        ),
    ]
