# Generated by Django 3.2.25 on 2024-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0020_rename_medicine_choice_medicine_medicine_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_choice',
            field=models.CharField(choices=[('Before Meal', 'Before Meal'), ('After Meal', 'After Meal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='time',
            field=models.CharField(choices=[('AM', 'AM'), ('NOON', 'NOON'), ('PM', 'PM')], max_length=100),
        ),
    ]
