# Generated by Django 3.2.25 on 2024-07-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0021_auto_20240706_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Medicalhistory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
