# Generated by Django 3.2.25 on 2024-07-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0022_alter_patient_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventappointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='q1bapp.user'),
            preserve_default=False,
        ),
    ]
