# Generated by Django 3.2.25 on 2024-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q1bapp', '0024_medicinelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
